// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication_API.Data;

#nullable disable

namespace WebApplication_API.Migrations
{
    [DbContext(typeof(FirstapiContext))]
    partial class FirstapiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication_API.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MyProperty")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "F. Scott Fitzgerald",
                            MyProperty = 0,
                            Title = "The Great Gatsby",
                            YearPublished = 1925
                        },
                        new
                        {
                            Id = 2,
                            Author = "Harper Lee",
                            MyProperty = 0,
                            Title = "To Kill a Mockingbird",
                            YearPublished = 1960
                        },
                        new
                        {
                            Id = 3,
                            Author = "George Orwell",
                            MyProperty = 0,
                            Title = "1984",
                            YearPublished = 1949
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jane Austen",
                            MyProperty = 0,
                            Title = "Pride and Prejudice",
                            YearPublished = 1813
                        },
                        new
                        {
                            Id = 5,
                            Author = "J.R.R. Tolkien",
                            MyProperty = 0,
                            Title = "The Hobbit",
                            YearPublished = 1937
                        },
                        new
                        {
                            Id = 6,
                            Author = "Herman Melville",
                            MyProperty = 0,
                            Title = "Moby-Dick",
                            YearPublished = 1851
                        },
                        new
                        {
                            Id = 7,
                            Author = "Aldous Huxley",
                            MyProperty = 0,
                            Title = "Brave New World",
                            YearPublished = 1932
                        },
                        new
                        {
                            Id = 8,
                            Author = "J.D. Salinger",
                            MyProperty = 0,
                            Title = "The Catcher in the Rye",
                            YearPublished = 1951
                        },
                        new
                        {
                            Id = 9,
                            Author = "Leo Tolstoy",
                            MyProperty = 0,
                            Title = "War and Peace",
                            YearPublished = 1869
                        },
                        new
                        {
                            Id = 10,
                            Author = "Fyodor Dostoevsky",
                            MyProperty = 0,
                            Title = "Crime and Punishment",
                            YearPublished = 1866
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
